### ISSUE TITLE
Trying to Log with ERROR level and this bug:

### ISSUE THREAD

**Issue by ohld** [parikls/python-telegram-logger#1]
```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/handlers.py", line 1478, in _monitor
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/handlers.py", line 1461, in handle
    handler.handle(record)
  File "/usr/local/lib/python3.7/site-packages/python_telegram_logger/handlers.py", line 109, in handle
    self.emit(record)
  File "/usr/local/lib/python3.7/site-packages/python_telegram_logger/handlers.py", line 116, in emit
    mode=self.formatter.MODE,
AttributeError: 'Formatter' object has no attribute 'MODE'```

**Comment by ohld** [comment]
Problem was in my config file: your library doesn't support the formatter:

``` json
log_config = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        'simple': {
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
        }
    },
    "handlers": {
        "telegram": {
            "class": "python_telegram_logger.Handler",
            "token": Config.TALEGRAM_TOKEN,
            "chat_ids": [Config.TELEGRAM_MONITORING_CHAT_ID],
            # "formatter": "simple",
            "level": "WARNING",
        },
         "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "level": "INFO",
        },
    },
    "root": {
        "handlers": ["telegram", "console"],
        "level": "INFO",
    }
}
```
